import { generateDailyPlanStream } from '@/lib/daily-plan-logic';
import { prisma } from '@/lib/prisma';
import { getTrialStatus } from '@/lib/trial-logic';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
       return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const userId = session.user.id;

    const body = await request.json();
    console.log('Received body:', body);

    const profile = await prisma.profile.findUnique({
      where: { userId },
      select: { trial_end_date: true, is_trial_active: true, is_subscribed: true }
    });

    console.log('Trial check - profile:', profile?.trial_end_date, 'is_subscribed:', profile?.is_subscribed)

    if (profile && profile.trial_end_date) {
      const tStatus = getTrialStatus(profile)
      if (tStatus.isExpired && !tStatus.isSubscribed) {
         return Response.json({ error: 'Trial expired. Please subscribe to continue.' }, { status: 403 });
      }
    }

    const payload = {
      user_id: userId,
      day_number: 1, // Currently only day 1 is explicitly generated by stream
      growth_plan_id: body.growth_plan_id
    };

    const stream = await generateDailyPlanStream(payload);
    return new Response(stream, { 
      headers: { 
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache, no-transform'
      } 
    });
  } catch (err: any) {
    console.error('[generate-daily-plan] error:', err);
    return Response.json({ error: err?.message || 'Internal Server Error' }, { status: 500 });
  }
}
